### ISSUE TITLE
CLI subcommand "archive list" does not provide any package listing

### ISSUE THREAD

**Issue by xrucka** [CESNET/ltp-api-client-lib#5]
Hello, I'm currently ressurecting some of my previous work on Archivematica interconnection to LTP, this time using this library. So far, I have noticed that in my case, CLI subcommand `archive list` does not provide any archive. This behavior matches the result obtained in web browser (using the cli reported URL https://ltp.cesnet.cz/api/v2/archive /?group=8de6d92fc5b4413d90cf759d6b19cd3d&limit=10 ). However, if I remove the limit from the URL, the packages get listed properly.

**Comment by spigi42** [comment]
Hello, thank you for your report. This issue should be fixed in this PR https://github.com/CESNET/ltp-api-client-lib/pull/6.
